import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {Provider} from "@/components/Widgets/Provider/Provider";
import Nav from "@/components/Navbar";
import {NextUIProvider} from "@nextui-org/react";
import {ReactNode} from "react";
import "./globals.css";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  export default function RootLayout({children} : {children: ReactNode}

  ){
  return (
    <html lang="en">
    <body className={inter.className}>
    <NextUIProvider>
      <Nav/>
      
      <Provider>
        {children}
      </Provider>
    </NextUIProvider>
    </body>
    </html>
  );
}
